spring:
  application:
    name: "opentelemetry-test-collector"
  grpc:
    server:
      port: ${GRPC_SERVER_PORT:4317}

server:
  port: ${HTTP_SERVER_PORT:4318}

springdoc:
  api-docs:
    path: /api-docs

com:
  github:
    siom79:
      opentelemetry-test-collector:
        traces:
          cache:
            size: ${TRACES_CACHE_SIZE:1000}
        metrics:
          cache:
            size: ${METRICS_CACHE_SIZE:1000}

